# 应用配置
app:
  name: "News API"
  version: "1.0.0"
  description: "提供日、周、月新闻查询接口"

# MongoDB配置
mongodb:
  host: "121.37.47.63"
  port: 27017
  username: "admin"
  password: "aa123aaqqA!"
  database: "eastmoney_news"
  collection: "news"

# JWT配置
jwt:
  secret_key: "bcb8b7160371aa0514fcba286c8c9e774eb854a76ab0c3dc9332c0b32cd3d936531d629db54d80edbab74008c4c33ea21f5a1ed99295282de4d5517ee51bd76f"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# 认证配置
auth:
  username: "admin"
  password: "sip@1234"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(funcName)s - %(lineno)d - %(message)s"
  file: "logs/app.log"
  backup_count: 30

# LLM配置
llm:
  provider: "deepseek"
  api_key: "sk-0534dba7771c44e1b89c7eb46c168dfd"
  model: "deepseek-chat"
  base_url: "https://api.deepseek.com"

# 盘后信息服务配置
after_market:
  news_api_url: "https://www.life233.top"
  news_api_username: "admin"
  news_api_password: "sip@1234"
  dingtalk_webhook: "https://oapi.dingtalk.com/robot/send?access_token=7c358aa51936f007c951ac2cf9387e235d1e845b5cd639837e9a884d483c6657"
  dingtalk_secret: "SEC1d98f39e4143ee506dc5cb059f8dc7f949f18576bde03f98d74595a2aa56f9dd"
  scheduler_time: "10:55"
  scheduler_timezone: "Asia/Shanghai"
