# Generated by Django 4.2.7 on 2025-11-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=7, verbose_name="颜色"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("level", models.IntegerField(default=1, verbose_name="层级")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_system", models.BooleanField(default=False, verbose_name="系统分类")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                        verbose_name="父分类",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题分类",
                "verbose_name_plural": "错题分类",
                "db_table": "category",
                "ordering": ["user", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_categories",
                        to="categories.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_categories",
                        to="questions.question",
                        verbose_name="错题",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题分类关联",
                "verbose_name_plural": "错题分类关联",
                "db_table": "question_category",
                "indexes": [
                    models.Index(
                        fields=["question", "category"],
                        name="question_ca_questio_5c8c37_idx",
                    ),
                    models.Index(
                        fields=["category", "question"],
                        name="question_ca_categor_e530a6_idx",
                    ),
                ],
                "unique_together": {("question", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "parent", "is_active"],
                name="category_user_id_2978f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_system", "is_active"], name="category_is_syst_0add6d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "name", "parent")},
        ),
    ]
