# Generated by Django 4.2.7 on 2025-11-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="答案内容")),
                ("explanation", models.TextField(blank=True, verbose_name="解释")),
                (
                    "steps",
                    models.JSONField(blank=True, default=list, verbose_name="解题步骤"),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=50, verbose_name="来源"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                ("likes_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("views_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="questions.question",
                        verbose_name="关联错题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "答案",
                "verbose_name_plural": "答案",
                "db_table": "answer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("likes_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="answers.answer",
                        verbose_name="所属答案",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="answers.answercomment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论者",
                    ),
                ),
            ],
            options={
                "verbose_name": "答案评论",
                "verbose_name_plural": "答案评论",
                "db_table": "answer_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="answer_images/", verbose_name="图片"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_images",
                        to="answers.answer",
                        verbose_name="所属答案",
                    ),
                ),
            ],
            options={
                "verbose_name": "答案图片",
                "verbose_name_plural": "答案图片",
                "db_table": "answer_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="answers.answercomment",
                        verbose_name="所属评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="点赞者",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论点赞",
                "verbose_name_plural": "评论点赞",
                "db_table": "comment_like",
                "indexes": [
                    models.Index(
                        fields=["comment", "user"],
                        name="comment_lik_comment_321837_idx",
                    )
                ],
                "unique_together": {("comment", "user")},
            },
        ),
        migrations.CreateModel(
            name="AnswerLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="answers.answer",
                        verbose_name="所属答案",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="点赞者",
                    ),
                ),
            ],
            options={
                "verbose_name": "答案点赞",
                "verbose_name_plural": "答案点赞",
                "db_table": "answer_like",
                "indexes": [
                    models.Index(
                        fields=["answer", "user"], name="answer_like_answer__f7c2dd_idx"
                    )
                ],
                "unique_together": {("answer", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="answercomment",
            index=models.Index(
                fields=["answer", "parent", "is_deleted"],
                name="answer_comm_answer__1f569f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="answercomment",
            index=models.Index(
                fields=["user", "created_at"], name="answer_comm_user_id_8ba683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "is_verified"], name="answer_questio_70492e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["user", "created_at"], name="answer_user_id_62c616_idx"
            ),
        ),
    ]
