# Generated by Django 4.2.7 on 2025-11-29 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="知识点名称")),
                ("level", models.IntegerField(default=1, verbose_name="层级")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="questions.knowledgepoint",
                        verbose_name="父知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
                "db_table": "knowledge_point",
                "ordering": ["subject", "level", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目标题")),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题"),
                            ("multiple_choice", "多选题"),
                            ("true_false", "判断题"),
                            ("fill_blank", "填空题"),
                            ("short_answer", "简答题"),
                            ("essay", "论述题"),
                            ("calculation", "计算题"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=dict, verbose_name="选项"),
                ),
                ("correct_answer", models.TextField(blank=True, verbose_name="正确答案")),
                ("user_answer", models.TextField(blank=True, verbose_name="用户答案")),
                ("analysis", models.TextField(blank=True, verbose_name="解析")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                        default=2,
                        verbose_name="难度",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("exam", "考试"),
                            ("homework", "作业"),
                            ("exercise", "练习"),
                            ("textbook", "教材"),
                            ("mock_exam", "模拟考"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "source_detail",
                    models.CharField(blank=True, max_length=100, verbose_name="来源详情"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片"),
                ),
                ("is_solved", models.BooleanField(default=False, verbose_name="是否已解决")),
                ("is_marked", models.BooleanField(default=False, verbose_name="是否标记")),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后复习时间"),
                ),
                ("review_count", models.IntegerField(default=0, verbose_name="复习次数")),
                (
                    "knowledge_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions",
                        to="questions.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题",
                "verbose_name_plural": "错题",
                "db_table": "question",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="学科名称")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=7, verbose_name="颜色"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "学科",
                "verbose_name_plural": "学科",
                "db_table": "subject",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                ("review_count", models.IntegerField(default=0, verbose_name="复习次数")),
                (
                    "last_reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后复习时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目统计",
                "verbose_name_plural": "题目统计",
                "db_table": "question_statistics",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False, verbose_name="是否答对")),
                ("review_time", models.IntegerField(default=0, verbose_name="复习用时(秒)")),
                ("notes", models.TextField(blank=True, verbose_name="复习笔记")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="复习时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="questions.question",
                        verbose_name="所属错题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="复习者",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题复习记录",
                "verbose_name_plural": "错题复习记录",
                "db_table": "question_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="question_images/", verbose_name="图片"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="是否主图")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_images",
                        to="questions.question",
                        verbose_name="所属错题",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目图片",
                "verbose_name_plural": "题目图片",
                "db_table": "question_image",
                "ordering": ["-is_main", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.subject",
                verbose_name="学科",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_points",
                to="questions.subject",
                verbose_name="所属学科",
            ),
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=7, verbose_name="颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目标签",
                "verbose_name_plural": "题目标签",
                "db_table": "question_tag",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="QuestionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="笔记内容")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="questions.question",
                        verbose_name="所属错题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题笔记",
                "verbose_name_plural": "错题笔记",
                "db_table": "question_note",
                "ordering": ["-created_at"],
                "unique_together": {("question", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["user", "created_at"], name="question_user_id_4f6259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "difficulty"], name="question_subject_208821_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_solved", "is_marked"], name="question_is_solv_ad7a56_idx"
            ),
        ),
    ]
