# Generated by Django 4.2.7 on 2025-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="images",
            field=models.TextField(blank=True, default="[]", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.TextField(blank=True, default="{}", verbose_name="选项"),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.TextField(blank=True, default="[]", verbose_name="标签"),
        ),
    ]
