# Generated by Django 4.2.7 on 2025-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "注册"),
                    ("login", "登录"),
                    ("logout", "登出"),
                    ("update_profile", "更新个人信息"),
                    ("create_question", "创建错题"),
                    ("update_question", "更新错题"),
                    ("delete_question", "删除错题"),
                    ("create_answer", "创建解答"),
                    ("update_answer", "更新解答"),
                    ("delete_answer", "删除解答"),
                    ("create_category", "创建分类"),
                    ("update_category", "更新分类"),
                    ("delete_category", "删除分类"),
                    ("search", "搜索"),
                    ("view", "查看"),
                    ("export", "导出"),
                    ("import", "导入"),
                ],
                max_length=50,
                verbose_name="操作",
            ),
        ),
    ]
