# Generated by Django 4.2.7 on 2025-11-30 11:52

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="details",
            field=apps.common.fields.SQLiteJSONField(
                blank=True, default=dict, verbose_name="详细信息"
            ),
        ),
    ]
