# Generated by Django 4.2.7 on 2025-11-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                to="categories.category",
                verbose_name="分类",
            ),
        ),
    ]
