# Generated by Django 4.2.7 on 2025-11-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(max_length=100, unique=True, verbose_name="关键词"),
                ),
                ("frequency", models.IntegerField(default=0, verbose_name="使用频率")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "搜索建议",
                "verbose_name_plural": "搜索建议",
                "db_table": "search_suggestion",
                "ordering": ["-frequency", "keyword"],
                "indexes": [
                    models.Index(
                        fields=["keyword"], name="search_sugg_keyword_c2fafb_idx"
                    ),
                    models.Index(
                        fields=["frequency"], name="search_sugg_frequen_1f4780_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(max_length=100, unique=True, verbose_name="关键词"),
                ),
                ("search_count", models.IntegerField(default=0, verbose_name="搜索次数")),
                (
                    "last_searched_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后搜索时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "热门搜索",
                "verbose_name_plural": "热门搜索",
                "db_table": "popular_search",
                "ordering": ["-search_count", "-last_searched_at"],
                "indexes": [
                    models.Index(
                        fields=["keyword"], name="popular_sea_keyword_2539dc_idx"
                    ),
                    models.Index(
                        fields=["search_count"], name="popular_sea_search__07e817_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=200, verbose_name="搜索关键词")),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="筛选条件"),
                ),
                ("results_count", models.IntegerField(default=0, verbose_name="结果数量")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                ("search_time", models.FloatField(default=0.0, verbose_name="搜索时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="搜索者",
                    ),
                ),
            ],
            options={
                "verbose_name": "搜索历史",
                "verbose_name_plural": "搜索历史",
                "db_table": "search_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="search_hist_user_id_352b9f_idx",
                    ),
                    models.Index(fields=["query"], name="search_hist_query_69a772_idx"),
                ],
            },
        ),
    ]
