# Generated by Django 4.2.7 on 2025-11-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_config",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("success", "成功"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统通知",
                "verbose_name_plural": "系统通知",
                "db_table": "system_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("success", "成功"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, verbose_name="关联对象类型"),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知",
                "verbose_name_plural": "用户通知",
                "db_table": "user_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="user_notifi_user_id_ee3bcf_idx",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="user_notifi_related_28a6cd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="操作动作")),
                ("resource_type", models.CharField(max_length=50, verbose_name="资源类型")),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="资源ID"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="operation_l_user_id_c9af97_idx",
                    ),
                    models.Index(
                        fields=["action", "resource_type"],
                        name="operation_l_action_c1e699_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="operation_l_resourc_989a89_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug反馈"),
                            ("feature", "功能建议"),
                            ("improvement", "改进建议"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("admin_reply", models.TextField(blank=True, verbose_name="管理员回复")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="反馈者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="feedback_user_id_8e9eb5_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="feedback_status_90e99d_idx",
                    ),
                ],
            },
        ),
    ]
