# Generated by Django 4.2.7 on 2025-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="extra_data",
            field=models.TextField(blank=True, default="{}", verbose_name="额外数据"),
        ),
    ]
