# Generated by Django 4.2.7 on 2025-11-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_categories"),
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_ai_generated",
            field=models.BooleanField(default=False, verbose_name="是否AI生成"),
        ),
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="是否正确"),
        ),
        migrations.AddField(
            model_name="answerimage",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
                verbose_name="关联错题",
            ),
        ),
    ]
