# Generated by Django 4.2.7 on 2025-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0002_add_is_ai_generated_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="images",
            field=models.TextField(blank=True, default="[]", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="steps",
            field=models.TextField(blank=True, default="[]", verbose_name="解题步骤"),
        ),
    ]
