# Generated by Django 4.2.7 on 2025-11-29 02:19

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="个人简介")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        default="",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=100, verbose_name="学校"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="已验证")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后登录IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "auth_user",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_question", "创建错题"),
                            ("update_question", "更新错题"),
                            ("delete_question", "删除错题"),
                            ("create_answer", "创建解答"),
                            ("update_answer", "更新解答"),
                            ("delete_answer", "删除解答"),
                            ("create_category", "创建分类"),
                            ("update_category", "更新分类"),
                            ("delete_category", "删除分类"),
                            ("search", "搜索"),
                            ("view", "查看"),
                            ("export", "导出"),
                            ("import", "导入"),
                        ],
                        max_length=50,
                        verbose_name="操作",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=50, verbose_name="对象类型"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对象ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=200, verbose_name="对象表示"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
            ],
            options={
                "verbose_name": "活动日志",
                "verbose_name_plural": "活动日志",
                "db_table": "user_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "device",
                    models.CharField(blank=True, max_length=100, verbose_name="设备"),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=100, verbose_name="浏览器"),
                ),
                (
                    "os",
                    models.CharField(blank=True, max_length=50, verbose_name="操作系统"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="位置"),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="登出时间"),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "db_table": "user_login_log",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_preference",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                        default=2,
                        verbose_name="难度偏好",
                    ),
                ),
                ("daily_target", models.IntegerField(default=5, verbose_name="每日目标")),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="总错题数"),
                ),
                (
                    "solved_questions",
                    models.IntegerField(default=0, verbose_name="已解决错题数"),
                ),
                ("study_days", models.IntegerField(default=0, verbose_name="学习天数")),
                (
                    "consecutive_days",
                    models.IntegerField(default=0, verbose_name="连续学习天数"),
                ),
                (
                    "last_study_date",
                    models.DateField(blank=True, null=True, verbose_name="最后学习日期"),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
                "db_table": "user_profile",
            },
        ),
    ]
