# Generated by Django 4.2.7 on 2025-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_useractivitylog_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="details",
            field=models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
        ),
    ]
